### PR TITLE
Changes for TAP2WAV.C to compile on MacOS (not tested on Windows or Linux)

### PR DESCRIPTION
**Pull request by BrettHallen**
I got your TAP2WAV.C to compile on macOS Sonoma 14.5 by making some minor adjustments (you can find them with "BH" comments).  I noticed that you must use -R option otherwise it gets stuck in a loop so have forced raw_mode = 1 always (no need for -R option).

I tested the resulting WAV files by loading on to my Праветц 8Д (Pravetz 8D) - they loaded without issue.
/Brett.

----------------------------
For interest, these were the initial errors when trying to compile on MacOS with clang:
----------------------------
### ERROR 1
tap2wav.c:87:1: error: type specifier missing, defaults to 'int'; ISO C99 and later do not support implicit int [-Wimplicit-int]
init(int argc, char *argv[])
^
int
### ERROR 2
tap2wav.c:92:9: error: call to undeclared library function 'strcmp' with type 'int (const char *, const char *)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
    if (strcmp(argv[i],"-8")==0) speed=8000;
        ^
tap2wav.c:92:9: note: include the header <string.h> or explicitly provide a declaration for 'strcmp'
### ERROR 3
tap2wav.c:94:11: error: call to undeclared function 'stricmp'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        else if (stricmp(argv[i],"-R")==0) raw_mode=1;
                 ^
### ERROR 4
tap2wav.c:114:1: error: type specifier missing, defaults to 'int'; ISO C99 and later do not support implicit int [-Wimplicit-int]
main(int argc,char *argv[])
^
int
### ERROR 5
tap2wav.c:124:5: error: call to undeclared library function 'exit' with type 'void (int) __attribute__((noreturn))'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
    exit(1);
    ^
tap2wav.c:124:5: note: include the header <stdlib.h> or explicitly provide a declaration for 'exit'
### ERROR 6
tap2wav.c:164:2: error: expected '}'
}
 ^
tap2wav.c:115:1: note: to match this '{'
{
^
6 errors generated.

### CODE REVIEW

**Comment by norayr** [comment]
i checked, it doesn't compile on linux, but i also checked that the version currently on github also doesn't compile with newer gcc.

so right now i am merging this, thank you very much, and later i'll make sure it works both on linux and macos.

**Comment by BrettHallen** [comment]
Thanks.  I tried adding in compiler directives to separate the changes I had to make for MacOS (__MACH__) with the original code, for example:

```
#if defined __MACH__ /* compiling on MacOS */
  else if (strcasecmp(argv[i],"-R")==0) raw_mode=1; /* BH MacOS */
#else
  else if (stricmp(argv[i],"-R")==0) raw_mode=1;   /*  BH Windows */
#endif
```
Brett.

**Comment by BrettHallen** [comment]
BTW, thanks for the link to your Soviet-era programs - I converted them with TAP2WAV and loaded them on my Pravetz (not sure if you've [seen my video](https://youtu.be/mrQjGksSQUk)).  The "Electron" ones are related to a Soviet-era television called the Elektron TS-382 DPK (Электрон Ц-382 ДПК).

The "cassette menu" file has this to say:

> I am the "Pravetz-8D" computer. 
> "8" stands for 8-bit, "D" stands for domestic. 
> My homeland is Bulgaria.  
> I work together with the "Elektron 382 DPK" television.
> We have become very good friends.
> On the next page you will find the games we would love to play with you.
> We wish you a great game!

**Comment by norayr** [comment]
yes yes, 'elecktron' was the ukrainian ssr company which was importing pravetz computers from bulgaria and selling those together with their 'elektron' tv sets. because pravetz had this rgb connection, they had (i assume) a dedicated connection on their tv sets.

we (my parents) got a second hand pravetz back then, and someone helped us to make a dedicated port on our tv set.

on the program, i also made another commit, with which i believe it builds both on macos and on linux.

i asked my friend who has macos to test, and it built for him. but he cannot test if it works.

so if you'd like, try to test one day my last commit, i hope it'll also work. (:
